"""empty message

Revision ID: 3d9d76864bc8
Revises: 3fc54300ba11
Create Date: 2024-05-06 10:43:47.043071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9d76864bc8'
down_revision = '3fc54300ba11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hamburgers_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hamburgers_table', schema=None) as batch_op:
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
