"""remove price, add star rating

Revision ID: 6772282e3376
Revises: 5123f302bbdf
Create Date: 2024-07-31 10:59:42.186714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6772282e3376'
down_revision = '5123f302bbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delis_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_rating', sa.Integer(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delis_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('star_rating')

    # ### end Alembic commands ###
