"""empty message

Revision ID: a9db67ff7eac
Revises: df5a65685707
Create Date: 2024-02-15 10:40:16.322742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9db67ff7eac'
down_revision = 'df5a65685707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hamburgers_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('combo_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hamburgers_table', schema=None) as batch_op:
        batch_op.drop_column('combo_price')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
